export const data = [
  {
    doc_type: 1,
    source_type: 2,
    crawl_source: 1,
    crawl_source_code: 'pp',
    pub_time: 1737452864,
    crawl_time: 1737452974,
    subject_id: null,
    title: null,
    description: null,
    content:
      '❤️❤️❤️Em yêu khách nhà em lắm cơ sáng thù đi vệ sinh đường ống nước tới 12h45pút mới đc về chiều em lại đi lắp nước tại phúc thọ đây ạ❤️❤️❤️Giờ cứ phải trực tiếp mắt thấy tai nghe các Bác mới tin được🕵️🕵️🕵️\n🎗️Công Ty TNHH Thương Mại Và Xây Dựng L19 🎗️ \n🌱🌱🌱Theo tiến sĩ Martin Fox, - tác giả cuốn sách" Healthy water for a long life" ( Dịch ra tiếng Việt là " Nước lành mạnh " ) việc nuốt các chất độc hại từ nước uống có thể không phải là con đường phơi nhiễm chính.\n🆘🆘🆘Sự hấp thụ qua da đối với các chất độc hại -toluene, ethylbenzene, styrene- được kiểm chứng ở cả người lớn và trẻ em đều rất lớn. Chúng ta gặp rủi ro lớn khi tắm bồn \n♨️hoặc tắm vòi hoa sen do hít phải các chất ô nhiễm hoá học. Tỷ lệ phơi nhiễm qua đường hít này cao gấp nhiều lần so với uống trực tiếp ( từ 6-80 lần❌❌❌ tuỳ nồng độ và tính chất của hoá chất ) . Do vậy, nhiều nghiên cứu đã chỉ ra rằng, chúng ta nên xem xét một hệ thống lọc toàn bộ ngôi nhà để đảm bảo rằng nước tắm đã được loại bỏ hoàn toàn chất hữu cơ ( dạng dễ bay hơi ) để bảo vệ sức khoẻ tối đa.\nXu thế sống mới trong thời kỳ ô nhiễm môi trường khá nặng nề là lắp 1 hệ thống lọc tổng đầu nguồn. \n"🚿🚿🚿"ĐỪNG BIẾN DA VÀ HỆ HÔ HẤP THÀNH MÀNG LỌC KHÍ ĐỘC TỪ NƯỚC NÓNG BẠN NHÉ ""\n☔💧Nguồn Nước Máy nước Mưa nhà bạn đã đảm bảo an toàn vệ sinh chưa \n📝:Số nhà 45-Đường 422-Tân Lập -Đan Phượng -Hà Nội \n☎️:094.727.1122👉086.533.8695\n🕵️🕵️🕵️Các Bác soi hộ em như này đủ có Tâm và có Tầm chưa ạ🕵️🕵️🕵️',
    url: 'https://www.facebook.com/61561612727518_1537272330114794',
    media_urls: '[]',
    comments: 0,
    shares: 0,
    reactions: 0,
    favors: 0,
    views: 0,
    web_tags: '[]',
    web_keywords: '[]',
    auth_id: '61561612727518',
    auth_name: 'Công Ty TNHH Thương Mại và Xây Dựng L19',
    auth_type: 1,
    auth_url: 'https://www.facebook.com/61561612727518',
    source_id: '61561612727518',
    source_name: 'Công Ty TNHH Thương Mại và Xây Dựng L19',
    source_url: 'https://www.facebook.com/61561612727518',
    reply_to: null,
    level: null,
    sentiment: 0,
    '@timestamp': '2025-01-21T09:49:34.095Z',
    crawl_bot: 'search-002',
    mg_sync: false,
    org_id: 2,
  },
];
